apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio-creds
  namespace: minio-tenant
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gitlab-secret-store
  target:
    name: minio-creds
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.env: |
          export MINIO_ROOT_USER="{{ .root_user }}"
          export MINIO_ROOT_PASSWORD="{{ .root_password }}"
  data:
    - secretKey: root_user
      remoteRef:
        key: MINIO_ROOT_USER
    - secretKey: root_password
      remoteRef:
        key: MINIO_ROOT_PASSWORD
