apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-config
  labels:
    app.kubernetes.io/part-of: homelab
    platform.homelab/layer: security
    platform.homelab/category: config
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: 'https://github.com/nkester/homelab.git'
    targetRevision: argocd-deploy
    path: infrastructure/bootstrap/external-secrets
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
