apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: knative-operator
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: homelab
    platform.homelab/layer: serverless
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/knative/operator.git'
    targetRevision: knative-v1.14.0
    path: config/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: knative-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
