apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nkester/homelab.git'
    targetRevision: argocd-deploy
    path: infrastructure/storage/longhorn
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: longhorn-system
  ignoreDifferences:
    - group: apps
      kind: DaemonSet
      jsonPointers:
        - /status/numberReady
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
