apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio-tenant
  labels:
    app.kubernetes.io/part-of: homelab
    platform.homelab/layer: storage
    platform.homelab/category: tenant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: 'https://github.com/nkester/homelab.git'
    targetRevision: argocd-deploy
    path: infrastructure/storage/minio
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: minio-tenant
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
