apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-config
  labels:
    app.kubernetes.io/part-of: homelab
    platform.homelab/layer: bootstrap
    platform.homelab/category: config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/compare-options: ServerSideDiff=true
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/nkester/homelab.git'
    targetRevision: argocd-deploy
    path: argocd/system-config
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
